### ISSUE TITLE
HiFi-Gan support

### ISSUE THREAD

**Issue by loretoparisi** [tulasiram58827/TTS_TFLite#2]
Thank you for this project! 🥇 
I suggest to add the [HiFi-GAN](https://github.com/jik876/hifi-gan), since it has sota performances in generating wav from mel spectrogram. In my understanding, [TensorFlowTTS](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/hifigan) has recently added support to it.

**Comment by tulasiram58827** [comment]
I am working on it. Next model will be Hifi GAN

**Comment by tulasiram58827** [comment]
@loretoparisi Added HiFi GAN conversion notebook.

**Comment by loretoparisi** [comment]
Amazing thank you!
