### ISSUE TITLE
Implementation code on Android

### ISSUE THREAD

**Issue by Oskop** [tulasiram58827/TTS_TFLite#3]
Thanks for share the models.
I would like to know how you implements the model in Android.
Maybe you can make a tutorial in Medium for that.

@farmaker47 @khanhlvg

**Comment by sayakpaul** [comment]
Tagging in @farmaker47 @khanhlvg to know if they could provide a reference here.

**Comment by Oskop** [comment]
> 
> 
> Tagging in @farmaker47 @khanhlvg to know if they could provide a reference here.

Ok. Thanks.

**Comment by farmaker47** [comment]
Hi @Oskop if you are an android developer you can find useful info [here](https://www.tensorflow.org/lite/guide). Due to heavy work I do not know if implementing a model from the bunch inside android will be available in the near future. In case there will be one you will be notified. Thanks

**Comment by rafiuddinkhan** [comment]
@Oskop https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/android

**Comment by Oskop** [comment]
Thanks, folks.
