### ISSUE TITLE
HI-FI gan inference latency 

### ISSUE THREAD

**Issue by cookingbear** [tulasiram58827/TTS_TFLite#4]
I saw in README that hi-fi gan inference speed is 10x faster than that of multi-band melgan. Why is hi-fi gan so fast?

**Comment by tulasiram58827** [comment]
I am not sure of the actual reason. You can refer to the [HiFi GAN Paper](https://arxiv.org/abs/2010.05646) for more details. This is the quote from the paper "HiFi-GAN generates samples 13.4 times faster than real-time on CPU with comparable quality to an autoregressive counterpart."

**Comment by cookingbear** [comment]
> I am not sure of the actual reason. You can refer to the [HiFi GAN Paper](https://arxiv.org/abs/2010.05646) for more details. This is the quote from the paper "HiFi-GAN generates samples 13.4 times faster than real-time on CPU with comparable quality to an autoregressive counterpart."

yes I believe that it is 10x times faster than real-time on CPU with comparable quality to an autoregressive counterpart. But multi-band melgan is not an autoregressive model and it is already 10x times faster than its autoregressive counterpart(melgan). So I just feel it is wield.

**Comment by tulasiram58827** [comment]
Like I said I do not have much expertise on the HiFi GAN. You can use the HiFi GAN model from the repository and use this [benchmarking tool](https://www.tensorflow.org/lite/performance/measurement) to benchmark yourself. If you found out any discrepancy feel free to report. We used the same [benchmark tool](https://www.tensorflow.org/lite/performance/measurement) to benchmark all the models.

**Comment by cookingbear** [comment]
> Like I said I do not have much expertise on the HiFi GAN. You can use the HiFi GAN model from the repository and use this [benchmarking tool](https://www.tensorflow.org/lite/performance/measurement) to benchmark yourself. If you found out any discrepancy feel free to report. We used the same [benchmark tool](https://www.tensorflow.org/lite/performance/measurement) to benchmark all the models.

Thanks for the reply

**Comment by v-nhandt21** [comment]
> > Like I said I do not have much expertise on the HiFi GAN. You can use the HiFi GAN model from the repository and use this [benchmarking tool](https://www.tensorflow.org/lite/performance/measurement) to benchmark yourself. If you found out any discrepancy feel free to report. We used the same [benchmark tool](https://www.tensorflow.org/lite/performance/measurement) to benchmark all the models.
> 
> Thanks for the reply

Did you find the reason why hifigan gets 10 times faster than multiband melgan ?

I try benchmark provided checkpoint of hifigan, it takes up to 0.3s for inference.

https://github.com/tulasiram58827/TTS_TFLite/issues/12

Maybe there some mistake here  @cookingbear @tulasiram58827
