### ISSUE TITLE
error with HiFi-GAN, is the env problem?

### ISSUE THREAD

**Issue by tricky61** [tulasiram58827/TTS_TFLite#8]
Hi, first thank you for your tools, they are helpful to me.
but when I  use the HiFi-GAN.ipynb I got the following error:

  File "~/anaconda3/lib/python3.6/site-packages/onnx_tf/handlers/backend/conv_mixin.py", line 119, in <listcomp>
    for i in list(range(spatial_size))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

My env is  as follow:
torch: 1.4.0
onnx:1.5.0
onnx-tf:1.5.0
onnx-runtime:1.4.0
tensorflow:1.15.0

It seems onnx load model error after the torch.onnx.export model? so, have no relation with the tf or onnx_tf.

**Comment by sayakpaul** [comment]
Can you try running the Colab Notebooks? They are pre-configured eliminating the need to do a local setup.

**Comment by tulasiram58827** [comment]
Hey, @tricky61 I would suggest you to use Colab Notebooks. I think here error seems to be from `onnx-tensorflow` . Try installing `onnx-tensorflow-1.7`

**Comment by tricky61** [comment]
@sayakpaul @tulasiram58827  thanks for your reply. the Colab Notebooks will also depoly a new env in my computer, and install package will be bother. I will try to  update the onnx-tensorflow version.

**Comment by sayakpaul** [comment]
> Colab Notebooks will also depoly a new env in my computer

Not sure what you meant by this. The Colab Notebooks are supposed to run from a web browser like Google Chrome. How would that deploy a new environment?

**Comment by tulasiram58827** [comment]
You can use this link https://colab.research.google.com/github/tulasiram58827/TTS_TFLite/blob/main/HiFi-GAN.ipynb to open colab notebook in any browser directly and execute in the browser itself.

**Comment by tricky61** [comment]
@tulasiram58827 https://colab.research.google.com/github/tulasiram58827/TTS_TFLite/blob/main/HiFi-GAN.ipynb#scrollTo=AIjHAjzV1_E1
I think it's still the env probelm. when I ran pip install tf-nightly, there is the mismatch between torch, numpy
ERROR: torchvision 0.8.1+cu101 has requirement torch==1.7.0, but you'll have torch 1.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement numpy~=1.19.2, but you'll have numpy 1.17.4 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement tensorboard~=2.4, but you'll have tensorboard 2.0.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible
 when not run pip install tf-nightly, there will be error in the meldataset.py from meldataset import mel_spectrogram, MAX_WAV_VALUE, load_wav. some strange errors

**Comment by tulasiram58827** [comment]
Hey @tricky61 

I just re-ran the notebook and noticed the error. It is due to numba version mismatch. Committed the fix.

- Please run the notebook sequentially.
- Also you need to restart the kernel after 1st code block.

**Comment by tricky61** [comment]
@tulasiram58827 Thanks for your reply and your update, it works.
